#!/bin/sh

# test-compare-outputs.sh - Compare analyze-dune-project skill outputs for Unix/Linux
#
# SYNOPSIS
#   ./test-compare-outputs.sh <powershell-output> <shell-output>
#
# DESCRIPTION
#   Validates that the PowerShell and shell analysis helpers produce equivalent output.
#   Normalizes path separators, ignores line-ending differences, and reports any real
#   discrepancies in section ordering or content.
#
# PARAMETERS
#   $1: Path to the output file generated by analyze-project.ps1
#   $2: Path to the output file generated by analyze-project.sh
#
# EXAMPLE
#   ./test-compare-outputs.sh /tmp/analysis-ps1.txt /tmp/analysis-sh.txt

set -euf

if [ "$#" -ne 2 ]; then
    printf 'usage: %s POWERSHELL_OUTPUT SHELL_OUTPUT\n' "$0" >&2
    exit 2
fi

ps_output="$1"
sh_output="$2"

# Normalize a single line by removing leading .\ and converting \ to /
normalize_line() {
    local line="$1"
    if [ "${line#=== }" != "$line" ]; then
        # This is a header line; normalize it
        # Remove leading === and trailing ===
        local body="${line#=== }"
        body="${body%% ===}"
        # Remove leading ./
        body="${body#./}"
        # Remove leading .\
        body="${body#.\\}"
        # Convert \ to /
        body="${body//\\/\/}"
        printf '=== %s ===\n' "$body"
    else
        printf '%s\n' "$line"
    fi
}

# Normalize a file: convert CRLF to LF and apply normalize_line to each line
normalize_file() {
    local file="$1"
    # Convert CRLF to LF, then apply line normalization
    tr -d '\r' < "$file" | while IFS= read -r line || [ -n "$line" ]; do
        normalize_line "$line"
    done
}

# Check that files exist
if [ ! -f "$ps_output" ]; then
    printf 'error: PowerShell output file not found: %s\n' "$ps_output" >&2
    exit 1
fi

if [ ! -f "$sh_output" ]; then
    printf 'error: Shell output file not found: %s\n' "$sh_output" >&2
    exit 1
fi

printf 'Loading PowerShell output: %s\n' "$ps_output"
ps_normalized=$(mktemp)
trap "rm -f '$ps_normalized'" EXIT

printf 'Loading shell output: %s\n' "$sh_output"
sh_normalized=$(mktemp)
trap "rm -f '$ps_normalized' '$sh_normalized'" EXIT

normalize_file "$ps_output" > "$ps_normalized"
normalize_file "$sh_output" > "$sh_normalized"

# Count lines
ps_lines=$(wc -l < "$ps_normalized")
sh_lines=$(wc -l < "$sh_normalized")

printf '\n'
printf 'PowerShell output: %d lines\n' "$ps_lines"
printf 'Shell output: %d lines\n' "$sh_lines"

# Extract and compare section headers
ps_headers=$(grep '^=== .* ===$' "$ps_normalized" || true)
sh_headers=$(grep '^=== .* ===$' "$sh_normalized" || true)

ps_section_count=$(echo "$ps_headers" | grep -c . || true)
sh_section_count=$(echo "$sh_headers" | grep -c . || true)

printf '\n'
printf 'PowerShell sections: %d\n' "$ps_section_count"
printf 'Shell sections: %d\n' "$sh_section_count"

if [ "$ps_section_count" -ne "$sh_section_count" ]; then
    printf 'error: Section count mismatch!\n' >&2
    exit 1
fi

# Compare headers
if ! diff -q <(echo "$ps_headers") <(echo "$sh_headers") > /dev/null 2>&1; then
    printf 'error: Section header mismatch detected:\n' >&2
    diff -u <(echo "$ps_headers") <(echo "$sh_headers") || true
    exit 1
fi

printf '✓ Section headers match exactly\n'

# Compare full content line-by-line
if ! diff -q "$ps_normalized" "$sh_normalized" > /dev/null 2>&1; then
    printf '\n'
    printf 'Content differences detected:\n'
    diff -u "$ps_normalized" "$sh_normalized" | head -40 || true
    printf 'error: Content mismatch! Review above for details.\n' >&2
    exit 1
fi

printf '✓ File content matches exactly\n'
printf '\n'
printf '✅ All validations passed!\n'
printf 'PowerShell and shell outputs are equivalent.\n'
