param(
    [Parameter(Mandatory = $true)]
    [string]$PowerShellOutput,

    [Parameter(Mandatory = $true)]
    [string]$ShellOutput
)

<#
.SYNOPSIS
Compares PowerShell and shell helper outputs for the analyze-dune-project skill.

.DESCRIPTION
This script validates that the PowerShell and shell analysis helpers produce equivalent
output. It normalizes path separators, ignores line-ending differences, and reports
any real discrepancies in section ordering or content.

.PARAMETER PowerShellOutput
Path to the output file generated by analyze-project.ps1

.PARAMETER ShellOutput
Path to the output file generated by analyze-project.sh

.EXAMPLE
./test-compare-outputs.ps1 -PowerShellOutput "C:\Temp\analysis-ps1.txt" -ShellOutput "C:\Temp\analysis-sh.txt"
#>

$ErrorActionPreference = 'Stop'

function Normalize-Row {
    param([string]$Line)
    if ($Line -like '=== * ===') {
        # Extract header body, normalize paths, and reconstruct
        $body = $Line.Substring(4, $Line.Length - 8)
        $body = $body -replace '^\.\\', ''      # Remove leading .\
        $body = $body -replace '^\./', ''       # Remove leading ./
        $body = $body -replace '\\', '/'        # Convert \ to /
        return "=== $body ==="
    }
    return $Line
}

function Get-NormalizedLines {
    param([string]$Path)
    # Read file and split by newline, handling both LF and CRLF
    $text = [System.IO.File]::ReadAllText($Path)
    $text = $text -replace "`r`n", "`n"  # Normalize CRLF to LF
    return @($text -split "`n" | ForEach-Object { Normalize-Row $_ })
}

# Load both files
Write-Host "Loading PowerShell output: $PowerShellOutput"
if (-not (Test-Path $PowerShellOutput)) {
    Write-Error "PowerShell output file not found: $PowerShellOutput"
    exit 1
}
$psLines = Get-NormalizedLines $PowerShellOutput

Write-Host "Loading shell output: $ShellOutput"
if (-not (Test-Path $ShellOutput)) {
    Write-Error "Shell output file not found: $ShellOutput"
    exit 1
}
$shLines = Get-NormalizedLines $ShellOutput

# Compare line counts
Write-Host ""
Write-Host "PowerShell output: $($psLines.Count) lines"
Write-Host "Shell output: $($shLines.Count) lines"

# Extract and compare section headers
$psHeaders = @($psLines | Where-Object { $_ -like '=== * ===' })
$shHeaders = @($shLines | Where-Object { $_ -like '=== * ===' })

Write-Host ""
Write-Host "PowerShell sections: $($psHeaders.Count)"
Write-Host "Shell sections: $($shHeaders.Count)"

if ($psHeaders.Count -ne $shHeaders.Count) {
    Write-Error "Section count mismatch!"
    exit 1
}

# Compare headers
$headerDiff = Compare-Object $psHeaders $shHeaders -SyncWindow 0
if ($headerDiff) {
    Write-Error "Section header mismatch detected:"
    $headerDiff | Format-Table -AutoSize | Out-String | Write-Error
    exit 1
}

Write-Host "✓ Section headers match exactly"

# Compare full content line-by-line
$diff = Compare-Object $psLines $shLines -SyncWindow 0
if ($diff) {
    Write-Host ""
    Write-Host "Content differences detected:"
    $diff | Select-Object -First 20 | Format-Table -AutoSize | Out-String | Write-Host
    Write-Error "Content mismatch! Review above for details."
    exit 1
}

Write-Host "✓ File content matches exactly"
Write-Host ""
Write-Host "✅ All validations passed!"
Write-Host "PowerShell and shell outputs are equivalent."
